# 🐳 AI Agent Platform - Infrastructure Services

services:
  # 🗄️ PostgreSQL - Primary Database
  postgres:
    image: postgres:15-alpine
    container_name: clever_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: clever_db
      POSTGRES_USER: clever_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./tools/deployment/init-scripts:/docker-entrypoint-initdb.d # Commented out until the configuration file is created
    networks:
      - clever_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clever_user -d clever_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ⚡ Redis - Caching & Session Storage
  redis:
    image: redis:7-alpine
    container_name: clever_redis
    restart: unless-stopped
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      # - ./tools/deployment/redis.conf:/usr/local/etc/redis/redis.conf # Commented out until the configuration file is created
    networks:
      - clever_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # 🧠 Qdrant - Vector Database for Semantic Search
  qdrant:
    image: qdrant/qdrant:v1.12.0
    container_name: clever_qdrant
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - qdrant_data:/qdrant/storage
      # - ./tools/deployment/qdrant-config.yaml:/qdrant/config/production.yaml # Commented out until the configuration file is created
    networks:
      - clever_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 15s
      timeout: 10s
      retries: 3

  # 📊 Jaeger - Distributed Tracing (Optional for Development)
  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: clever_jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP collector
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    networks:
      - clever_network
    profiles:
      - monitoring

  # 📈 Prometheus - Metrics Collection (Optional for Development)
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: clever_prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      # - ./tools/deployment/prometheus.yml:/etc/prometheus/prometheus.yml # Commented out until the configuration file is created
    networks:
      - clever_network
    profiles:
      - monitoring

  # 📊 Grafana - Metrics Visualization (Optional for Development)
  grafana:
    image: grafana/grafana:11.2.0
    container_name: clever_grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # - ./tools/deployment/grafana:/etc/grafana/provisioning # Commented out until the configuration file is created
    networks:
      - clever_network
    profiles:
      - monitoring
    depends_on:
      - prometheus

# 📁 Persistent Storage Volumes
volumes:
  postgres_data:
    name: clever_postgres_data
  redis_data:
    name: clever_redis_data
  qdrant_data:
    name: clever_qdrant_data
  prometheus_data:
    name: clever_prometheus_data
  grafana_data:
    name: clever_grafana_data

# 🌐 Networks
networks:
  clever_network:
    name: clever_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16